### ISSUE TITLE
在Linux上动态库无法加载问题

### ISSUE THREAD

**Issue by 54huaxiao** [JaySon-Huang/pyjpegtbx#17]
在Linux上安装了jpeg9c  libjpeg.so还是无法编译

**Comment by JaySon-Huang** [comment]
@MoHuaxiao 是无法编译 libjpeg 还是无法使用这个python库？
刚刚尝试了下，修复了加载 libc 库的问题。可以再试下是否能够顺利运行。

附上我的步骤：
```
# Build libjpeg library
wget http://www.ijg.org/files/jpegsrc.v9c.tar.gz
tar xvf jpegsrc.v9c.tar.gz && cd jpeg-9c
./configure && make
cd ..
# Copy libjpeg library to path
cp ./jpeg-9c/.libs/libjpeg.so ./pyjpegtbx/
cd pyjpegtbx
LD_LIBRARY_PATH=.:$LD_LIBRARY_PATH python3 example.py
```

> You can directly use `python3 example.py` without setting LD_LIBRARY_PATH if you apply `make install` for libjpeg

**Comment by qibao77** [comment]
> @MoHuaxiao 是无法编译 libjpeg 还是无法使用这个python库？
> 刚刚尝试了下，修复了加载 libc 库的问题。可以再试下是否能够顺利运行。
> 
> 附上我的步骤：
> 
> ```
> # Build libjpeg library
> wget http://www.ijg.org/files/jpegsrc.v9c.tar.gz
> tar xvf jpegsrc.v9c.tar.gz && cd jpeg-9c
> ./configure && make
> cd ..
> # Copy libjpeg library to path
> cp ./jpeg-9c/.libs/libjpeg.so ./pyjpegtbx/
> cd pyjpegtbx
> LD_LIBRARY_PATH=.:$LD_LIBRARY_PATH python3 example.py
> ```
> 
> > You can directly use `python3 example.py` without setting LD_LIBRARY_PATH if you apply `make install` for libjpeg

您好，linux上按您这个步骤操作后，运行python3 example.py还是不能加载动态库

**Comment by JaySon-Huang** [comment]
https://github.com/JaySon-Huang/pyjpegtbx/blob/master/pyjpegtbx/functions.py#L27-L28
在这里加上一行 `print("try to load {}".format(libname))`，然后运行，把运行时具体的输出打印出来看看？ @qibao77

**Comment by qibao77** [comment]
> https://github.com/JaySon-Huang/pyjpegtbx/blob/master/pyjpegtbx/functions.py#L27-L28
> 在这里加上一行 `print("try to load {}".format(libname))`，然后运行，把运行时具体的输出打印出来看看？ @qibao77

结果是这样的：
try to load libjpeg.dll
try to load libjpeg.so
try to load c.dll
try to load libc.so
try to load libc.dylib
Traceback (most recent call last):
  File "example.py", line 6, in <module>
    from pyjpegtbx import JPEGImage
  File "/pyjpegtbx-libjpeg-9c/pyjpegtbx/__init__.py", line 21, in <module>
    from .functions import jfuncs, cfopen, cfclose, jround_up
  File "/pyjpegtbx-libjpeg-9c/pyjpegtbx/functions.py", line 41, in <module>
    _c = __loadLib(_all_libs[1])
  File "/pyjpegtbx-libjpeg-9c/pyjpegtbx/functions.py", line 35, in __loadLib
    raise ImportError("ERROR: fail to load the dynamic library.")
ImportError: ERROR: fail to load the dynamic library.

**Comment by JaySon-Huang** [comment]
看起来是 libc 加载失败。在输出里面没有 "try to load libc.so.6"的输出，能 check 一下你的 `functions.py` 里面，_all_libs 是否有包含 "libc.so.6"么？
```
_all_libs = (
    ('libjpeg.dll', 'libjpeg.so', 'libjpeg.dylib'),
    ( 'libc.so.6', 'c.dll', 'libc.so', 'libc.dylib'),
)
```

如果没有的话，补上；如果有的话，把 'libc.so.6' 提到 tuple 里的第一位，再试试运行？

**Comment by qibao77** [comment]
> 看起来是 libc 加载失败。在输出里面没有 "try to load libc.so.6"的输出，能 check 一下你的 `functions.py` 里面，_all_libs 是否有包含 "libc.so.6"么？
> 
> ```
> _all_libs = (
>     ('libjpeg.dll', 'libjpeg.so', 'libjpeg.dylib'),
>     ( 'libc.so.6', 'c.dll', 'libc.so', 'libc.dylib'),
> )
> ```
> 
> 如果没有的话，补上；如果有的话，把 'libc.so.6' 提到 tuple 里的第一位，再试试运行？

加上后就可以成功运行了，感谢🙏

**Comment by JaySon-Huang** [comment]
Going to close this issue. Feel free to comment if you happen to this error again.
